# Generated by Django 4.1.2 on 2022-11-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_currencymodel_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymodel',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='myapp.changemodel'),
        ),
    ]
